### ISSUE TITLE
Build error with Python 3.8

### ISSUE THREAD

**Issue by varunhiremath** [enthought/enable#375]
Hello,

I maintain the python-enable package in Debian and was trying to update it to the latest release 4.8.1 and build with Python 3.8, but have run into some build errors. Could you please take a look at the below build log and let me know if I'm missing anything?
```
compile options: '-Ikiva -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.8 -c'
x86_64-linux-gnu-g++: kiva/_hit_test.cpp
x86_64-linux-gnu-g++: kiva/_cython_speedups.cpp
In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1830,
                 from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from kiva/_cython_speedups.cpp:612:
/usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
kiva/_cython_speedups.cpp: In function 'int __Pyx_InitCachedConstants()':
kiva/_cython_speedups.cpp:20106:75: error: invalid conversion from 'int' to 'PyObject*' {aka '_object*'} [-fpermissive]
20106 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
kiva/_cython_speedups.cpp:332:37: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                     ^
kiva/_cython_speedups.cpp:20106:234: error: invalid conversion from 'PyObject*' {aka '_object*'} to 'int' [-fpermissive]
20106 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
      |                                                                                                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                                                                                          |
      |                                                                                                                                                                                                                                          PyObject* {aka _object*}
kiva/_cython_speedups.cpp:332:69: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                     ^~~~
kiva/_cython_speedups.cpp:20106:263: error: invalid conversion from 'int' to 'PyObject*' {aka '_object*'} [-fpermissive]
20106 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
      |                                                                                                                                                                                                                                                                       ^
      |                                                                                                                                                                                                                                                                       |
      |                                                                                                                                                                                                                                                                       int
kiva/_cython_speedups.cpp:332:75: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                           ^~~~~
kiva/_cython_speedups.cpp:332:86: error: too many arguments to function 'PyCodeObject* PyCode_New(int, int, int, int, int, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*)'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                                      ^
kiva/_cython_speedups.cpp:20106:34: note: in expansion of macro '__Pyx_PyCode_New'
20106 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
      |                                  ^~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/compile.h:5,
                 from /usr/include/python3.8/Python.h:138,
                 from kiva/_cython_speedups.cpp:4:
/usr/include/python3.8/code.h:122:28: note: declared here
  122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
      |                            ^~~~~~~~~~
kiva/_cython_speedups.cpp:20171:75: error: invalid conversion from 'int' to 'PyObject*' {aka '_object*'} [-fpermissive]
20171 |   __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
kiva/_cython_speedups.cpp:332:37: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                     ^
kiva/_cython_speedups.cpp:20171:227: error: invalid conversion from 'PyObject*' {aka '_object*'} to 'int' [-fpermissive]
20171 |   __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
      |                                                                                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                                                                                   |
      |                                                                                                                                                                                                                                   PyObject* {aka _object*}
kiva/_cython_speedups.cpp:332:69: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                     ^~~~
kiva/_cython_speedups.cpp:20171:256: error: invalid conversion from 'int' to 'PyObject*' {aka '_object*'} [-fpermissive]
20171 |   __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
      |                                                                                                                                                                                                                                                                ^
      |                                                                                                                                                                                                                                                                |
      |                                                                                                                                                                                                                                                                int
kiva/_cython_speedups.cpp:332:75: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                           ^~~~~
kiva/_cython_speedups.cpp:332:86: error: too many arguments to function 'PyCodeObject* PyCode_New(int, int, int, int, int, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*)'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                                      ^
kiva/_cython_speedups.cpp:20171:34: note: in expansion of macro '__Pyx_PyCode_New'
20171 |   __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
      |                                  ^~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/compile.h:5,
                 from /usr/include/python3.8/Python.h:138,
                 from kiva/_cython_speedups.cpp:4:
/usr/include/python3.8/code.h:122:28: note: declared here
  122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
      |                            ^~~~~~~~~~
kiva/_cython_speedups.cpp: In function 'PyCodeObject* __Pyx_CreateCodeObjectForTraceback(const char*, int, int, const char*)':
kiva/_cython_speedups.cpp:23055:9: error: invalid conversion from 'PyObject*' {aka '_object*'} to 'int' [-fpermissive]
23055 |         py_funcname,  /*PyObject *name,*/
      |         ^~~~~~~~~~~
      |         |
      |         PyObject* {aka _object*}
kiva/_cython_speedups.cpp:332:69: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                     ^~~~
kiva/_cython_speedups.cpp:23056:9: error: invalid conversion from 'int' to 'PyObject*' {aka '_object*'} [-fpermissive]
23056 |         py_line,
      |         ^~~~~~~
      |         |
      |         int
kiva/_cython_speedups.cpp:332:75: note: in definition of macro '__Pyx_PyCode_New'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                           ^~~~~
kiva/_cython_speedups.cpp:332:86: error: too many arguments to function 'PyCodeObject* PyCode_New(int, int, int, int, int, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*)'
  332 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
      |                                                                                      ^
kiva/_cython_speedups.cpp:23042:15: note: in expansion of macro '__Pyx_PyCode_New'
23042 |     py_code = __Pyx_PyCode_New(
      |               ^~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/compile.h:5,
                 from /usr/include/python3.8/Python.h:138,
                 from kiva/_cython_speedups.cpp:4:
/usr/include/python3.8/code.h:122:28: note: declared here
  122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
      |                            ^~~~~~~~~~
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:773: UserWarning: Specified path /usr/X11R6/lib64 is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:773: UserWarning: Specified path /usr/X11R6/lib is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:773: UserWarning: Specified path /usr/X11/lib64 is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:773: UserWarning: Specified path /usr/X11/lib is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:773: UserWarning: Specified path /usr/lib64 is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/X11R6/include is invalid.
  return self.get_paths(self.section, key)
/usr/lib/python3/dist-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/X11/include is invalid.
  return self.get_paths(self.section, key)
error: Command "x86_64-linux-gnu-g++ -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -O0 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ikiva -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.8 -c kiva/_cython_speedups.cpp -o build/temp.linux-amd64-3.8/kiva/_cython_speedups.o -MMD -MF build/temp.linux-amd64-3.8/kiva/_cython_speedups.o.d" failed with exit status 1
E: pybuild pybuild:341: build: plugin distutils failed with: exit code=1: /usr/bin/python3.8 setup.py build 
dh_auto_build: pybuild --build -i python{version} -p "3.8 3.7" returned exit code 13
make: *** [debian/rules:10: build] Error 255
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

Thanks,
Varun

**Comment by mdickinson** [comment]
I believe the problem is that `PyCode_New` differs from Python version to Python version, so the calls to it in `_cython_speedups.cpp` that are appropriate for Python 3.6 don't work on later Python versions.

Possibly the short-term fix is simply to regenerate the `_cython_speedups.cpp` file. A longer-term fix, to avoid similar problems in the future, would be to make Cython a build-time requirement and always regenerate the .cpp sources at build time.

**Comment by mdickinson** [comment]
@varunhiremath Do you have Cython in your build environment? And if so, what version? I'm wondering whether the problem is simply that your Cython is too old to know about the changes to `PyCode_New` in Python 3.8.

**Comment by mdickinson** [comment]
Related: https://github.com/cython/cython/issues/2938

**Comment by mdickinson** [comment]
> I'm wondering whether the problem is simply that your Cython is too old to know about the changes to `PyCode_New` in Python 3.8.

No; I was thrown by the fact that the enable build _requires_ Cython to be present in the build environment, but isn't actually using it for `_cython_speedups.pyx`. So it's our bundled `_cython_speedups.cpp` that's the cause of the issue; we need to regenerate with current Cython.

BTW, I'd expect things to be fine on Python 3.7; it should only be Python 3.8 that's problematic w.r.t. `PyCode_New`. I'm able to `pip install enable` into a Python 3.7 venv without problems, but I see the same issues as you when attempting to install into a Python 3.8 venv.

**Comment by varunhiremath** [comment]
Hi @mdickinson,

Thanks for looking into this issue so quickly. You are right, the current build failure is with Python 3.8. And cython version 0.29.14 is in the Debian build environment.

Thanks,
Varun

**Comment by mdickinson** [comment]
Okay, that makes sense. Then I think #376 should fix the issue. I leave it up to the maintainers to decide when the fix can be included in a release.

**Comment by mdickinson** [comment]
Let's leave this open until it's fixed in master (i.e., until #376 is merged).
