### PR TITLE
Use unittest as test runner instead of nose

### LINKED ISSUE #426: Use unittest as the test runner instead of nose
`nose` is no longer supported and it is wise to replaec it with `unittest` as the test runner. Note that in order to use `unittest` as the test runner, we will need to rename a number of test modules e.g. `container_test_case` needs to be `test_container` to ensure that `unittest` can discover the tests.

https://github.com/enthought/enable/blob/f8b3a21a0b7b94ecfb2788bd152f17889531f751/ci/edmtool.py#L248-L251

### PR DESCRIPTION
**Pull request by aaronayres35**
fixes #426 

This PR simply updates edmtool to run using unittest instead of nose, and changes test file names to ensure they get discovered.

### CODE REVIEW

**Comment by aaronayres35** [comment]
CI is failing with:
```
======================================================================
ERROR: testURLFallback (enable.savage.svg.tests.test_document.TestBrushFromColourValue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/enable/savage/svg/tests/test_document.py", line 69, in testURLFallback
    self.document.getBrushFromState().color,
  File "/home/travis/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/enable/savage/svg/document.py", line 880, in getBrushFromState
    element = self.dereference(url)
  File "/home/travis/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/enable/savage/svg/document.py", line 344, in dereference
    element = resources.open_svg(uri)
  File "/home/travis/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/enable/savage/svg/document.py", line 191, in open_svg
    f = open(path)
  File "/home/travis/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/enable/savage/svg/document.py", line 183, in <lambda>
    return path, lambda uri: BytesIO(urllib.request.urlopen(uri).read())
AttributeError: module 'urllib' has no attribute 'request'
----------------------------------------------------------------------
```

**Comment by kitchoi** [comment]
This PR is going to create some trivial merge conflicts with #455. Is it okay if we merge #455 first?

**Comment by aaronayres35** [comment]
> ~This PR is going to create some trivial merge conflicts with #455.~ Merging #455 is going to create some trivial merge conflicts for this PR. Is it okay if we merge #455 first?

Yep, go right ahead!

**Comment by kitchoi** [comment]
> Yep, go right ahead!

Thank you. Done.

File: kiva/tests/test_graphics_context.py [hunk 1]
```diff
@@ -4,8 +4,18 @@
...
+    from hypothesis import given
+    from hypothesis.strategies import sampled_from
+    hypothesis_available = True
+except ModuleNotFoundError:
+    def given(_):
+        def func(_):
+            pass
+        return func
+    def sampled_from(_):
+        pass
```
Comment (aaronayres35) [inline kiva/tests/test_graphics_context.py:17]: this was a bit awkward, but because `given` and `sampled_from` are used in decorators, so even if I try to skip those tests when `hypothesis_available == False` the tests still fail when trying to load them with something like:
```
======================================================================
ERROR: kiva.tests.test_graphics_context (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: kiva.tests.test_graphics_context
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/aayres/Desktop/enable/kiva/tests/test_graphics_context.py", line 27, in <module>
    class TestAlphaBlackImage(unittest.TestCase):
  File "/Users/aayres/Desktop/enable/kiva/tests/test_graphics_context.py", line 33, in TestAlphaBlackImage
    @given(sampled_from([1.0, 0.0, 0.5]))
NameError: name 'given' is not defined
```

There is probably a cleaner more standard way to do this sort of thing?  I am not sure

Comment (kitchoi) [reply kiva/tests/test_graphics_context.py:17]: `hypothesis` is a test dependency. I am not sure we need to skip these. We should make sure the test dependency is included in the `setup.py` though. CI does have `hypothesis` installed and these tests are run there.

File: enable/tests/test_test_assistant.py [hunk 2]
```diff
@@ -0,0 +1,78 @@
+import unittest
+from unittest import mock
+
+from enable.component import Component
+from enable.testing import EnableTestAssistant, _MockWindow
+from enable.tests._testing import skip_if_null
+
```
Comment (kitchoi) [inline enable/tests/test_test_assistant.py:7]: 🤖  Flake8: Two blank lines here.

File: enable/tests/test_test_assistant.py [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+        self.assertEqual(event.x, 10)
+        self.assertEqual(event.y, 20)
+        self.assertIsInstance(event.window, _MockWindow)
+        self.assertFalse(event.alt_down)
+        self.assertFalse(event.control_down)
+        self.assertFalse(event.shift_down)
+        self.assertEqual(event.window.get_pointer_position(), (10, 20))
+
+
```
Comment (kitchoi) [inline enable/tests/test_test_assistant.py:23]: 🤖  Too many blank lines here. (I will stop being flake8.)

File: kiva/agg/tests/test_gcmem.py [hunk 4]
```diff
@@ -6,8 +6,14 @@
...
 from kiva.image import GraphicsContext, GraphicsContextSystem
-from etsdevtools.debug.memusage import get_mem_usage
+try:
+    from etsdevtools.debug.memusage import get_mem_usage
+    etsdevtools_available = True
+except ModuleNotFoundError:
+    etsdevtools_available = False
 
+
+@unittest.skipIf(not etsdevtools_available, "test requires etsdevtools")
```
Comment (kitchoi) [inline kiva/agg/tests/test_gcmem.py:16]: I couldn't find the skip message in the log. I believe that's because test discovery does not use the `test_suite` and `test` functions below, and none of the methods in this test case has a name with the prefix `test_`: they start with the prefix `check_` instead.  Not sure if we still need to keep this `check_` prefix.  Could we remove the `test_suite`, `test`  and the `__main__` block below, and rename the method to `test_...` please?  Such change would be within the scope of this PR because this PR changes how tests are discovered. The tests will still be skipped, though.

File: kiva/tests/test_graphics_context.py (hunk 1 above)
Comment (kitchoi) [reply kiva/tests/test_graphics_context.py:17]: To elaborate on why I am not sure we need to skip tests based on missing test dependencies: TraitsUI has `packaging` as its test dependency, and it was specified in `extras_require`. Whenever I do `pip install traitsui` and try to run the test suite, I am greeted with an import error due to missing `packaging`: The tests requiring `packaging` are not skipped because `packaging` is not available. That import error reminds me to reinstall with `pip install traitsui[test]`.  If the test suite was permissive about missing test dependencies, then I risk forgetting to install those dependencies and end up running much fewer tests.

Test dependencies are still separated from optional dependencies due to optional features of the tested system (e.g. ArrayEditor is an optional feature of TraitsUI that depends on NumPy). When a package has optional features with optional dependencies, it is expected to be able to run the tests in the absence of those dependencies.

File: kiva/agg/tests/test_save.py [hunk 5]
```diff
@@ -3,14 +3,12 @@
...
 
-import nose
-
 from kiva import agg
 
 
 # FIXME:
 #   These tests are broken, and Peter promised to fix it at some point.
-
+@unittest.skip("tests are broken")
```
Comment (kitchoi) [inline kiva/agg/tests/test_save.py:11]: 😂  Do you mind opening an issue and reference it here please?

File: kiva/agg/tests/test_save.py [hunk 6]
```diff
@@ -3,14 +3,12 @@
 
 from numpy import allclose, ravel
 
-import nose
-
 from kiva import agg
 
 
 # FIXME:
 #   These tests are broken, and Peter promised to fix it at some point.
```
Comment (jwiggins) [inline kiva/agg/tests/test_save.py:10]: Might be better to just delete these tests? Peter Wang hasn't worked on this code for a long time. I'm _nearly certain_ that he has no interest in fixing these tests.

**Review by kitchoi — COMMENTED** [review]
Mostly LGTM. Some minor questions / suggestions. I have not compared the number of tests run before and after this change though.

File: kiva/agg/tests/test_save.py (hunk 6 above)
Comment (kitchoi) [reply kiva/agg/tests/test_save.py:10]: I noticed that only two of the four tests actually fail. It could also be a platform dependent behaviour, though.

Comment (kitchoi) [reply kiva/agg/tests/test_save.py:10]: FTR, these are the two tests that fail:
```
======================================================================
FAIL: test_bgr24_format (kiva.agg.tests.test_save.Test_Save)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/.edm/envs/enable-test-3.6-pyqt5-pillow/lib/python3.6/site-packages/kiva/agg/tests/test_save.py", line 23, in test_bgr24_format
    self.do_check_format('bgr24')
  File "/Users/kchoi/.edm/envs/enable-test-3.6-pyqt5-pillow/lib/python3.6/site-packages/kiva/agg/tests/test_save.py", line 43, in do_check_format
    self.format_output_map[fmt])
AssertionError: Lists differ: [255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 0, 0] != [255, 255, 255, 255, 255, 255, 0, 0, 255, 0, 0, 255]

First differing element 6:
255
0

- [255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 0, 0]
?                                              ------

+ [255, 255, 255, 255, 255, 255, 0, 0, 255, 0, 0, 255]
?                                ++++++


======================================================================
FAIL: test_bgra32_format (kiva.agg.tests.test_save.Test_Save)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/.edm/envs/enable-test-3.6-pyqt5-pillow/lib/python3.6/site-packages/kiva/agg/tests/test_save.py", line 29, in test_bgra32_format
    self.do_check_format('bgra32')
  File "/Users/kchoi/.edm/envs/enable-test-3.6-pyqt5-pillow/lib/python3.6/site-packages/kiva/agg/tests/test_save.py", line 43, in do_check_format
    self.format_output_map[fmt])
AssertionError: Lists differ: [255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 0, 0, 255] != [255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255]

First differing element 8:
255
0

- [255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 0, 0, 255]
?                                               ------          ------

+ [255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255]
?                                          ++++++          ++++++
```

File: kiva/agg/tests/test_gcmem.py (hunk 4 above)
Comment (aaronayres35) [reply kiva/agg/tests/test_gcmem.py:16]: Should I also add `etsdevtools` as a test dependency like what was done for `hypothesis`?

File: kiva/agg/tests/test_save.py (hunk 5 above)
Comment (aaronayres35) [reply kiva/agg/tests/test_save.py:11]: opened #480

File: kiva/agg/tests/test_gcmem.py (hunk 4 above)
Comment (kitchoi) [reply kiva/agg/tests/test_gcmem.py:16]: Er... `etsdevtools` is a worse dependency here. Let's not go there, and kill this test in a separate PR. This PR should aim at minimal changes in the number of tests being run: the purpose is to switch test runner. It is not meaningful to keep this test given it has not been exercised, but that's orthogonal.

File: kiva/agg/tests/test_save.py (hunk 5 above)
Comment (kitchoi) [reply kiva/agg/tests/test_save.py:11]: Thank you.
```suggestion
@unittest.skip("tests are broken. See enthought/enable#480")
```

**Review by kitchoi — APPROVED** [review]
Thank you.
(One minor suggestion in https://github.com/enthought/enable/pull/475/files#r539141323, as I forgot to submit it as a part of a batch review)

File: kiva/agg/tests/test_gcmem.py (hunk 4 above)
Comment (aaronayres35) [reply kiva/agg/tests/test_gcmem.py:16]: opened #483
