### ISSUE TITLE
Building enable with pip install on Linux + Python 3.8+ fails 

### ISSUE THREAD

**Issue by kitchoi** [enthought/enable#450]
The build works on Python 3.6 and Python 3.7, but not on Python 3.8 and Python 3.9.

OS: Ubuntu 18
Python versions: 3.8, 3.9
Enable version: 4.8.1 (as on PyPI)

Here is an except for part of the error logged:
```
2020-11-26T12:14:32.6448058Z     kiva/_cython_speedups.cpp: In function ‘int __Pyx_InitCachedConstants()’:
2020-11-26T12:14:32.6449435Z     kiva/_cython_speedups.cpp:20106:75: error: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
2020-11-26T12:14:32.6451096Z        __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
2020-11-26T12:14:32.6452976Z     kiva/_cython_speedups.cpp:332:37: note: in definition of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6453768Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6454327Z                                          ^
2020-11-26T12:14:32.6455259Z     kiva/_cython_speedups.cpp:332:86: error: invalid conversion from ‘PyObject* {aka _object*}’ to ‘int’ [-fpermissive]
2020-11-26T12:14:32.6456344Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6456949Z                                                                                           ^
2020-11-26T12:14:32.6457578Z     kiva/_cython_speedups.cpp:20106:34: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6458718Z        __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
2020-11-26T12:14:32.6459762Z                                       ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6460482Z     kiva/_cython_speedups.cpp:332:86: error: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
2020-11-26T12:14:32.6461162Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6461604Z                                                                                           ^
2020-11-26T12:14:32.6462228Z     kiva/_cython_speedups.cpp:20106:34: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6463364Z        __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
2020-11-26T12:14:32.6464339Z                                       ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6465427Z     kiva/_cython_speedups.cpp:332:86: error: too many arguments to function ‘PyCodeObject* PyCode_New(int, int, int, int, int, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*)’
2020-11-26T12:14:32.6466381Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6466838Z                                                                                           ^
2020-11-26T12:14:32.6467444Z     kiva/_cython_speedups.cpp:20106:34: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6468592Z        __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(3, 0, 6, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_cython_speedups_pyx, __pyx_n_s_points_in_polygon, 6, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0, 6, __pyx_L1_error)
2020-11-26T12:14:32.6469563Z                                       ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6470286Z     In file included from /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/compile.h:5:0,
2020-11-26T12:14:32.6471077Z                      from /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/Python.h:138,
2020-11-26T12:14:32.6471716Z                      from kiva/_cython_speedups.cpp:4:
2020-11-26T12:14:32.6472364Z     /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/code.h:122:28: note: declared here
2020-11-26T12:14:32.6473039Z      PyAPI_FUNC(PyCodeObject *) PyCode_New(
2020-11-26T12:14:32.6473460Z                                 ^~~~~~~~~~
2020-11-26T12:14:32.6474293Z     kiva/_cython_speedups.cpp:20171:75: error: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
2020-11-26T12:14:32.6475716Z        __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
2020-11-26T12:14:32.6477193Z     kiva/_cython_speedups.cpp:332:37: note: in definition of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6477918Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6478401Z                                          ^
2020-11-26T12:14:32.6479478Z     kiva/_cython_speedups.cpp:332:86: error: invalid conversion from ‘PyObject* {aka _object*}’ to ‘int’ [-fpermissive]
2020-11-26T12:14:32.6480362Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6480960Z                                                                                           ^
2020-11-26T12:14:32.6481881Z     kiva/_cython_speedups.cpp:20171:34: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6483214Z        __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
2020-11-26T12:14:32.6484361Z                                       ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6485205Z     kiva/_cython_speedups.cpp:332:86: error: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
2020-11-26T12:14:32.6485973Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6486501Z                                                                                           ^
2020-11-26T12:14:32.6487208Z     kiva/_cython_speedups.cpp:20171:34: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6488757Z        __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
2020-11-26T12:14:32.6490245Z                                       ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6491801Z     kiva/_cython_speedups.cpp:332:86: error: too many arguments to function ‘PyCodeObject* PyCode_New(int, int, int, int, int, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*)’
2020-11-26T12:14:32.6493352Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6493980Z                                                                                           ^
2020-11-26T12:14:32.6494901Z     kiva/_cython_speedups.cpp:20171:34: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6496531Z        __pyx_codeobj__38 = (PyObject*)__Pyx_PyCode_New(3, 0, 5, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__37, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__38)) __PYX_ERR(2, 1, __pyx_L1_error)
2020-11-26T12:14:32.6497920Z                                       ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6498637Z     In file included from /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/compile.h:5:0,
2020-11-26T12:14:32.6499633Z                      from /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/Python.h:138,
2020-11-26T12:14:32.6500400Z                      from kiva/_cython_speedups.cpp:4:
2020-11-26T12:14:32.6501213Z     /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/code.h:122:28: note: declared here
2020-11-26T12:14:32.6502031Z      PyAPI_FUNC(PyCodeObject *) PyCode_New(
2020-11-26T12:14:32.6502562Z                                 ^~~~~~~~~~
2020-11-26T12:14:32.6503839Z     kiva/_cython_speedups.cpp: In function ‘PyCodeObject* __Pyx_CreateCodeObjectForTraceback(const char*, int, int, const char*)’:
2020-11-26T12:14:32.6505343Z     kiva/_cython_speedups.cpp:332:86: error: invalid conversion from ‘PyObject* {aka _object*}’ to ‘int’ [-fpermissive]
2020-11-26T12:14:32.6506322Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6506924Z                                                                                           ^
2020-11-26T12:14:32.6507733Z     kiva/_cython_speedups.cpp:23042:15: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6508388Z          py_code = __Pyx_PyCode_New(
2020-11-26T12:14:32.6508787Z                    ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6509803Z     kiva/_cython_speedups.cpp:332:86: error: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
2020-11-26T12:14:32.6510681Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6511276Z                                                                                           ^
2020-11-26T12:14:32.6512063Z     kiva/_cython_speedups.cpp:23042:15: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6512705Z          py_code = __Pyx_PyCode_New(
2020-11-26T12:14:32.6513117Z                    ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6514522Z     kiva/_cython_speedups.cpp:332:86: error: too many arguments to function ‘PyCodeObject* PyCode_New(int, int, int, int, int, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*)’
2020-11-26T12:14:32.6515795Z                PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
2020-11-26T12:14:32.6516529Z                                                                                           ^
2020-11-26T12:14:32.6517137Z     kiva/_cython_speedups.cpp:23042:15: note: in expansion of macro ‘__Pyx_PyCode_New’
2020-11-26T12:14:32.6517620Z          py_code = __Pyx_PyCode_New(
2020-11-26T12:14:32.6517935Z                    ^~~~~~~~~~~~~~~~
2020-11-26T12:14:32.6518424Z     In file included from /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/compile.h:5:0,
2020-11-26T12:14:32.6519123Z                      from /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/Python.h:138,
2020-11-26T12:14:32.6519659Z                      from kiva/_cython_speedups.cpp:4:
2020-11-26T12:14:32.6520235Z     /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/code.h:122:28: note: declared here
2020-11-26T12:14:32.6520802Z      PyAPI_FUNC(PyCodeObject *) PyCode_New(
2020-11-26T12:14:32.6521379Z                                 ^~~~~~~~~~
2020-11-26T12:14:32.6524095Z     error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ikiva -I/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8 -c kiva/_cython_speedups.cpp -o build/temp.linux-x86_64-3.8/kiva/_cython_speedups.o -MMD -MF build/temp.linux-x86_64-3.8/kiva/_cython_speedups.o.d" failed with exit status 1
2020-11-26T12:14:32.6526506Z     ----------------------------------------
2020-11-26T12:14:32.6529952Z ERROR: Command errored out with exit status 1: /opt/hostedtoolcache/Python/3.8.6/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qc_tgdyz/enable/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qc_tgdyz/enable/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wzt0zfhr/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hostedtoolcache/Python/3.8.6/x64/include/python3.8/enable Check the logs for full command output.
```

See logs (this is part of an integration test workflow bringing in chaco, and enable is a dependency of chaco):

For Python 3.8: 
[log38.txt](https://github.com/enthought/enable/files/5603011/log38.txt)

For Python 3.9: 
[log39.txt](https://github.com/enthought/enable/files/5603012/log39.txt)

This could well be an upstream issue, but I wanted to open an issue here for reference.

**Comment by kitchoi** [comment]
Closing as a duplicate of #375, which has been fixed in #376
Upon being able to reproduce the issue using the enable 4.8.1 released on PyPI, I am able to verify installation works on master.
